spring:
  main:
    banner-mode: off
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost:5432/adamain-db
    driverClassName: org.postgresql.Driver
    username: adamain-admin
    password: adamainadmin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    lock-retry-count: 10
    postgresql:
      transactional-lock: false