spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/adamain-db
    driver-class-name: org.postgresql.Driver
    username: adamain-admin
    password: adamainadmin
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db.migration