spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/adamain-db
    driver-class-name: org.postgresql.Driver
    username: adamain-admin
    password: adamainadmin
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db.migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/adamain
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: 'adamain-app'
      principal-attribute: 'preferred_username'

server:
  port: 8081